name: PHP 7.0
desc:
 - Install PHP 7.0 from REMI repository.
variables:
  timezone:
    name: Timezone
    desc: Set timezone in /etc/php.ini
    type: string
  user:
    name: PHP-FPM user
    desc: User that runs php-fpm process
    type: string
  group:
    name: PHP-FPM group
    desc: Group that runs php-fpm process
    type: string
  modules:
    name: Additional modules
    desc: Comma separated list of package names
    type: array
  params:
    name: php.ini params
    desc: |
      Array of objects with attirbutes `key` and  `value`.
      {key: expose_php, value: Off}
    type: array
  php_version:
    name: PHP version (default 7.0)
    type: string

dependencies:
 - { role: dogpro.user_exist }
