---
- name: GATHER OS SPECIFIC VARS
  include_vars: "{{ item }}"
  with_first_found:
    - "../../../vars/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "../../../vars/{{ ansible_distribution }}.yml"
    - "../../../vars/{{ ansible_os_family }}.yml"

- include: centos.yml
  when: ansible_distribution == "CentOS"

- include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: PHP | ENABLE FPM
  service: name={{ php_fpm_service }} state=started enabled=yes

- name: PHP | SET OWNERSHIP
  file: path=/var/lib/php/session owner={{ user }} group={{ user }} state=directory
  notify: restart php-fpm
